In [1]:
#!/usr/bin/env python
# coding: utf-8

# # New-2DLIFV-PROMETHEE

import numpy as np

def Eudistance(a,b,t,t1):
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; # 输入两个2DLIFVs的值
    result1=pow(pow(u1-v1,2)/2+pow(u2-v2,2)/2,1/2)/t;
    result2=pow(pow(u3-v3,2)/2+pow(u4-v4,2)/2,1/2)/t1;
    result=(result1+result2)/2;
    return result

In [2]:
def cosimilar(a,b,t,t1):
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; # 输入两个2DLIFVs的值
    result1=(u1*v1+u2*v2)/(pow(u1*u1+u2*u2,1/2)*pow(v1*v1+v2*v2,1/2));
    result2=(u3*v3+u4*v4)/(pow(u3*u3+u4*u4,1/2)*pow(v3*v3+v4*v4,1/2));
    result=(result1+result2)/2;
    return result


In [3]:
def distance(a,b,t,t1):
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; # 输入两个2DLIFVs的值
    result=(2*np.arccos(cosimilar(a,b,t,t1))/np.pi+Eudistance(a,b,t,t1))/2;
    return result
def satdgree(a,t,t1):
    maxelement=[t,0,t1,0]
    u1=a[0];u2=a[1];u3=a[2];u4=a[3]; # 输入两个2DLIFVs的值
    result=1-distance(a,maxelement,t,t1);
    return result
def Sat(a,t,t1):
    maxelement=[t,0,t1,0]
    result=np.zeros(len(a))
    for i in range(len(a)):
            result[i]=1-distance(a[i],maxelement,t,t1)  
    return(result)
def Satmatrix(R,t,t1):
    maxelement=[t,0,t1,0]
    result=np.zeros(len(R)*len(R[0])).reshape(len(R[0]),len(R))
    for i in range(len(R)):
        result[:,i]=Sat(R[i],t,t1)
    return result

In [4]:

def P1(Cn):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]:
                re[j,i]=0
            else:
                re[j,i]=1
    return re

def P2(Cn,q):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<= S[j]+q:
                re[j,i]=0
            else:
                re[j,i]=1
    return re

def P3(Cn,p):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]:
                re[j,i]=0
            elif S[i]>=S[j]+p:   
                re[j,i]=1
            else:
                re[j,i]=(S[i]-S[j])/p
    return re
def P4(Cn,p,q):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]+q:
                re[j,i]=0
            elif S[i]>=S[j]+p:   
                re[j,i]=1
            else:
                re[j,i]=0.5
    return re

def P5(Cn,p,q):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]+q:
                re[j,i]=0
            elif S[i]>=S[j]+p:   
                re[j,i]=1
            else:
                re[j,i]=(S[i]-S[j]-q)/(p-q)
    return re


def P6(Cn,sigma=1):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]:
                re[j,i]=0
            else:
                re[j,i]=round(1-np.exp(-pow(S[i]-S[j],2)/(2*pow(sigma,2))),4)
    return re

In [5]:
e2a11=[2,5,1,3]
e2a21=[4,1,2,1]
e2a31=[2,3,1,1]
e2a41=[5,2,3,1]
e2C1=[e2a11,e2a21,e2a31,e2a41]
e2C1



e2a12=[4,2,2,1]
e2a22=[2,4,2,1]
e2a32=[4,1,1,1]
e2a42=[3,5,1,2]
e2C2=[e2a12,e2a22,e2a32,e2a42]
e2C2





e2a13=[2,3,1,1]
e2a23=[2,3,2,1]
e2a33=[4,1,2,1]
e2a43=[3,4,2,1]
e2C3=[e2a13,e2a23,e2a33,e2a43]
e2C3





e2a14=[2,4,2,1]
e2a24=[3,4,1,2]
e2a34=[3,1,1,2]
e2a44=[4,2,2,1]
e2C4=[e2a14,e2a24,e2a34,e2a44]
e2C4


R2=[e2C1,e2C2,e2C3,e2C4]    #专家E1的决策矩阵R1
R2
w=[0.30,0.30, 0.25, 0.15]

In [6]:
def CCw0(w,cw0):
    cw1=w[1]*(1-cw0)/(1-w[0])
    cw2=w[2]*(1-cw0)/(1-w[0])
    cw3=w[3]*(1-cw0)/(1-w[0])
    cw=(cw0,cw1,cw2,cw3)
    return cw

In [7]:
def CCw1(w,cw1):
    cw0=w[0]*(1-cw1)/(1-w[1])
    cw2=w[2]*(1-cw1)/(1-w[1])
    cw3=w[3]*(1-cw1)/(1-w[1])
    cw=(cw0,cw1,cw2,cw3)
    return cw

In [8]:
def CCw2(w,cw2):
    cw0=w[0]*(1-cw2)/(1-w[2])
    cw1=w[1]*(1-cw2)/(1-w[2])
    cw3=w[3]*(1-cw2)/(1-w[2])
    cw=(cw0,cw1,cw2,cw3)
    return cw

In [9]:
def CCw3(w,cw3):
    cw0=w[0]*(1-cw3)/(1-w[3])
    cw1=w[1]*(1-cw3)/(1-w[3])
    cw2=w[2]*(1-cw3)/(1-w[3])
    cw=(cw0,cw1,cw2,cw3)
    return cw

In [10]:
def netflow1(w,cw0):
    PI=CCw0(w,cw0)[0]*P5(e2C1,0.25,0.1)+CCw0(w,cw0)[1]*P4(e2C2,0.25,0.1)+CCw0(w,cw0)[2]*P6(e2C3,0.3)+CCw0(w,cw0)[3]*P3(e2C4,0.25)
    negative=np.sum(PI,axis=1)
    positive=np.sum(PI,axis=0)
    PINET=np.sum(PI,axis=0)-np.sum(PI,axis=1)
    rank=np.argsort(-PINET)+1
    return (PINET, rank)

In [11]:
ww=np.linspace(0,1,21)

In [12]:
# sensitivity analysis of attribute(C1) weight 
sentiment1=[]
for i in ww:
    sentiment1.append(netflow1(w,i))
sentiment1

[(array([ 0.43230408, -0.64781693,  0.57999569, -0.36448284]),
  array([3, 1, 4, 2], dtype=int64)),
 (array([ 0.2847902 , -0.51542608,  0.47689458, -0.24625869]),
  array([3, 1, 4, 2], dtype=int64)),
 (array([ 0.13727632, -0.38303524,  0.37379347, -0.12803455]),
  array([3, 1, 4, 2], dtype=int64)),
 (array([-0.01023756, -0.25064439,  0.27069236, -0.00981041]),
  array([3, 4, 1, 2], dtype=int64)),
 (array([-0.15775143, -0.11825354,  0.16759125,  0.10841373]),
  array([3, 4, 2, 1], dtype=int64)),
 (array([-0.30526531,  0.0141373 ,  0.06449014,  0.22663787]),
  array([4, 3, 2, 1], dtype=int64)),
 (array([-0.45277919,  0.14652815, -0.03861097,  0.34486201]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.60029307,  0.278919  , -0.14171208,  0.46308616]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.74780695,  0.41130984, -0.24481319,  0.5813103 ]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.89532082,  0.54370069, -0.3479143 ,  0.69953444]),
  array([4, 2, 3, 1], dtype=int64)),


In [13]:
def netflow2(w,cw1):
    PI=CCw1(w,cw1)[0]*P5(e2C1,0.25,0.1)+CCw1(w,cw1)[1]*P4(e2C2,0.25,0.1)+CCw1(w,cw1)[2]*P6(e2C3,0.3)+CCw1(w,cw1)[3]*P3(e2C4,0.25)
    negative=np.sum(PI,axis=1)
    positive=np.sum(PI,axis=0)
    PINET=np.sum(PI,axis=0)-np.sum(PI,axis=1)
    rank=np.argsort(-PINET)+1
    return (PINET, rank)

In [14]:
# sensitivity analysis of attribute(C2) weight 
sentiment2=[]
for i in ww:
    sentiment2.append(netflow2(w,i))
sentiment2

[(array([-1.28968456,  0.42361164, -0.48372996,  1.34980288]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-1.15020033,  0.37743106, -0.40954346,  1.18231273]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-1.0107161 ,  0.33125048, -0.33535697,  1.01482259]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.87123187,  0.2850699 , -0.26117047,  0.84733245]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.73174765,  0.23888931, -0.18698397,  0.6798423 ]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.59226342,  0.19270873, -0.11279747,  0.51235216]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.45277919,  0.14652815, -0.03861097,  0.34486201]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.31329496,  0.10034757,  0.03557552,  0.17737187]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.17381073,  0.05416699,  0.10976202,  0.00988173]),
  array([3, 2, 4, 1], dtype=int64)),
 (array([-0.03432651,  0.0079864 ,  0.18394852, -0.15760842]),
  array([3, 2, 1, 4], dtype=int64)),


In [15]:
def netflow3(w,cw2):
    PI=CCw2(w,cw2)[0]*P5(e2C1,0.25,0.1)+CCw2(w,cw2)[1]*P4(e2C2,0.25,0.1)+CCw2(w,cw2)[2]*P6(e2C3,0.3)+CCw2(w,cw2)[3]*P3(e2C4,0.25)
    negative=np.sum(PI,axis=1)
    positive=np.sum(PI,axis=0)
    PINET=np.sum(PI,axis=0)-np.sum(PI,axis=1)
    rank=np.argsort(-PINET)+1
    return (PINET, rank)

In [16]:
sentiment3=[]
for i in ww:
    sentiment3.append(netflow3(w,i))
sentiment3

[(array([-0.46763892,  0.2395042 , -0.2596813 ,  0.48781602]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.46466697,  0.22090899, -0.21546723,  0.45922522]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.46169503,  0.20231378, -0.17125317,  0.43063442]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.45872308,  0.18371857, -0.1270391 ,  0.40204362]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.45575114,  0.16512336, -0.08282504,  0.37345282]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.45277919,  0.14652815, -0.03861097,  0.34486201]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.44980724,  0.12793294,  0.00560309,  0.31627121]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.4468353 ,  0.10933773,  0.04981716,  0.28768041]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.44386335,  0.09074252,  0.09403122,  0.25908961]),
  array([4, 3, 2, 1], dtype=int64)),
 (array([-0.44089141,  0.07214731,  0.13824529,  0.23049881]),
  array([4, 3, 2, 1], dtype=int64)),


In [17]:
def netflow4(w,cw3):
    PI=CCw3(w,cw3)[0]*P5(e2C1,0.25,0.1)+CCw3(w,cw3)[1]*P4(e2C2,0.25,0.1)+CCw3(w,cw3)[2]*P6(e2C3,0.3)+CCw3(w,cw3)[3]*P3(e2C4,0.25)
    negative=np.sum(PI,axis=1)
    positive=np.sum(PI,axis=0)
    PINET=np.sum(PI,axis=0)-np.sum(PI,axis=1)
    rank=np.argsort(-PINET)+1
    return (PINET, rank)

In [18]:
sentiment4=[]
for i in ww:
    sentiment4.append(netflow4(w,i))
sentiment4

[(array([-0.47934358,  0.49047059,  0.01357888, -0.02470588]),
  array([2, 3, 4, 1], dtype=int64)),
 (array([-0.47048878,  0.37582311, -0.00381774,  0.09848342]),
  array([2, 4, 3, 1], dtype=int64)),
 (array([-0.46163399,  0.26117563, -0.02121436,  0.22167272]),
  array([2, 4, 3, 1], dtype=int64)),
 (array([-0.45277919,  0.14652815, -0.03861097,  0.34486201]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.44392439,  0.03188067, -0.05600759,  0.46805131]),
  array([4, 2, 3, 1], dtype=int64)),
 (array([-0.4350696 , -0.08276681, -0.07340421,  0.59124061]),
  array([4, 3, 2, 1], dtype=int64)),
 (array([-0.4262148 , -0.19741429, -0.09080082,  0.71442991]),
  array([4, 3, 2, 1], dtype=int64)),
 (array([-0.41736   , -0.31206177, -0.10819744,  0.83761921]),
  array([4, 3, 2, 1], dtype=int64)),
 (array([-0.40850521, -0.42670925, -0.12559406,  0.96080851]),
  array([4, 3, 1, 2], dtype=int64)),
 (array([-0.39965041, -0.54135673, -0.14299067,  1.08399781]),
  array([4, 3, 1, 2], dtype=int64)),
