In [1]:
# # New-2DLIFV-PROMETHEE
import numpy as np

In [2]:
# Euclidean distance for 2DLIFSs
def Eudistance(a,b,t,t1):
    """ a,b:  list, 
              2DLIFV
       t,t1:  int
              t+1 is the cardinality of H and t1+1 is the cardinality of S
    """
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; 
    result1=pow(pow(u1-v1,2)/2+pow(u2-v2,2)/2,1/2)/t;
    result2=pow(pow(u3-v3,2)/2+pow(u4-v4,2)/2,1/2)/t1;
    result=(result1+result2)/2;
    return result

In [3]:
# Example 3.1
A=[3,2,6,0]
B=[4,3,6,0]
C=[4,1,6,0]
D=[2,1,6,0]
E=[2,3,6,0]
Eudistance(A,B,10,6)

0.05

In [4]:
Eudistance(A,C,10,6)

0.05

In [5]:
Eudistance(A,D,10,6)

0.05

In [6]:
Eudistance(A,E,10,6)

0.05

In [7]:
# Cosine similarity for 2DLIFSs
def cosimilar(a,b,t,t1):
    """ a,b:  list, 
              2DLIFV
       t,t1:  int
              t+1 is the cardinality of H and t1+1 is the cardinality of S
    """
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; # 输入两个2DLIFVs的值
    result1=(u1*v1+u2*v2)/(pow(u1*u1+u2*u2,1/2)*pow(v1*v1+v2*v2,1/2));
    result2=(u3*v3+u4*v4)/(pow(u3*u3+u4*u4,1/2)*pow(v3*v3+v4*v4,1/2));
    result=(result1+result2)/2;
    return result

In [8]:
# Example 3.2
A=[3,3,6,0]
B=[4,4,6,0]
cosimilar(A,B,10,6)

1.0

In [9]:
# Example 3.3
A=[2,2,6,0]
B=[3,0,6,0]
C=[0,7,6,0]
cosimilar(A,B,10,6)

0.8535533905932737

In [10]:
cosimilar(A,C,10,6)

0.8535533905932737

In [11]:
#  Hybrid distance for 2DLIFSs
def distance(a,b,t,t1):
    """ a,b:  list, 
              2DLIFV
       t,t1:  int
              t+1 is the cardinality of H and t1+1 is the cardinality of S
    """
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; # 输入两个2DLIFVs的值
    result=(2*np.arccos(cosimilar(a,b,t,t1))/np.pi+Eudistance(a,b,t,t1))/2;
    return result

In [12]:
# Example 3.4
A=[3,2,6,0]
B=[4,3,6,0]
C=[4,1,6,0]
D=[2,1,6,0]
E=[2,3,6,0]

distance(A,B,10,6).round(4)

0.0375

In [13]:
distance(A,C,10,6).round(4)

0.102

In [14]:
distance(A,E,10,6).round(4)

0.1136

In [15]:
# Example 3.5

A=[3,3,6,0]
B=[4,4,6,0]

distance(A,B,10,6)

0.025

In [16]:
# Example 3.6
A=[2,2,6,0]
B=[3,0,6,0]
C=[0,7,6,0]
distance(A,B,10,6).round(4)

0.214

In [17]:
distance(A,C,10,6).round(4)

0.2696

In [18]:
# Satisfaction degree for 2DLIFVs
def satdgree(a,t,t1):
    """ a：   list, 
              2DLIFV
       t,t1:  int
              t+1 is the cardinality of H and t1+1 is the cardinality of S
    """    
    maxelement=[t,0,t1,0]
    u1=a[0];u2=a[1];u3=a[2];u4=a[3]; # 输入两个2DLIFVs的值
    result=1-distance(a,maxelement,t,t1);
    return result

In [19]:
# Example 4.1

A=[2,2,6,0]
B=[3,0,6,0]
C=[0,7,6,0]
satdgree(A,10,6).round(4)

0.6798

In [20]:
satdgree(B,10,6).round(4)

0.8763

In [21]:
satdgree(C,10,6).round(4)


0.4509

In [22]:
def Sat(a,t,t1):
    """ a：   list of list
              2DLIFVs
       t,t1:  int
              t+1 is the cardinality of H and t1+1 is the cardinality of S
    """      
    maxelement=[t,0,t1,0]
    result=np.zeros(len(a))
    for i in range(len(a)):
            result[i]=1-distance(a[i],maxelement,t,t1)  
    return(result)

In [23]:
def Satmatrix(R,t,t1):
    """ R：   array
              2DLIFVs
       t,t1:  int
              t+1 is the cardinality of H and t1+1 is the cardinality of S
    """  
    maxelement=[t,0,t1,0]
    result=np.zeros(len(R)*len(R[0])).reshape(len(R[0]),len(R))
    for i in range(len(R)):
        result[:,i]=Sat(R[i],t,t1)
    return result

In [24]:
# Example 6.1
#  decision matrix

e2a11=[2,5,1,3]
e2a21=[4,1,2,1]
e2a31=[2,3,1,1]
e2a41=[5,2,3,1]
e2C1=[e2a11,e2a21,e2a31,e2a41]
e2a12=[4,2,2,1]
e2a22=[2,4,2,1]
e2a32=[4,1,1,1]
e2a42=[3,5,1,2]
e2C2=[e2a12,e2a22,e2a32,e2a42]
e2C2
e2a13=[2,3,1,1]
e2a23=[2,3,2,1]
e2a33=[4,1,2,1]
e2a43=[3,4,2,1]
e2C3=[e2a13,e2a23,e2a33,e2a43]
e2C3
e2a14=[2,4,2,1]
e2a24=[3,4,1,2]
e2a34=[3,1,1,2]
e2a44=[4,2,2,1]
e2C4=[e2a14,e2a24,e2a34,e2a44]
e2C4
R2=[e2C1,e2C2,e2C3,e2C4]    
R2 # decision matrix

[[[2, 5, 1, 3], [4, 1, 2, 1], [2, 3, 1, 1], [5, 2, 3, 1]],
 [[4, 2, 2, 1], [2, 4, 2, 1], [4, 1, 1, 1], [3, 5, 1, 2]],
 [[2, 3, 1, 1], [2, 3, 2, 1], [4, 1, 2, 1], [3, 4, 2, 1]],
 [[2, 4, 2, 1], [3, 4, 1, 2], [3, 1, 1, 2], [4, 2, 2, 1]]]

In [25]:
# Improved preference functions
def P1(Cn):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]:
                re[j,i]=0
            else:
                re[j,i]=1
    return re
def P2(Cn,q):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<= S[j]+q:
                re[j,i]=0
            else:
                re[j,i]=1
    return re
def P3(Cn,p):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]:
                re[j,i]=0
            elif S[i]>=S[j]+p:   
                re[j,i]=1
            else:
                re[j,i]=(S[i]-S[j])/p
    return re
def P4(Cn,p,q):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]+q:
                re[j,i]=0
            elif S[i]>=S[j]+p:   
                re[j,i]=1
            else:
                re[j,i]=0.5
    return re
def P5(Cn,p,q):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]+q:
                re[j,i]=0
            elif S[i]>=S[j]+p:   
                re[j,i]=1
            else:
                re[j,i]=(S[i]-S[j]-q)/(p-q)
    return re
def P6(Cn,sigma=1):
    S=Sat(Cn,8,4)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if S[i]<=S[j]:
                re[j,i]=0
            else:
                re[j,i]=round(1-np.exp(-pow(S[i]-S[j],2)/(2*pow(sigma,2))),4)
    return re


In [26]:
# the weight vector of attributes.
w=[0.30,0.30, 0.25, 0.15]

In [27]:
# Table 3: Results of comprehensive preference degree
PI=w[0]*P5(e2C1,0.25,0.1)+w[1]*P4(e2C2,0.25,0.1)+w[2]*P6(e2C3,0.3)+w[3]*P3(e2C4,0.25)
PI

array([[0.        , 0.309075  , 0.23511704, 0.42057902],
       [0.21078791, 0.        , 0.25133394, 0.150425  ],
       [0.00120397, 0.3       , 0.        , 0.40853299],
       [0.3       , 0.15      , 0.184675  , 0.        ]])

In [28]:
# Table 4: Results of the 2DLIF flows Ψ+, Ψ− and ΨN
positive=np.sum(PI,axis=0) 
print("positive flows", positive)
print("positive flows rank",np.argsort(-positive)+1)
negative=np.sum(PI,axis=1)
print("negative flows", negative)
print("negative flows rank",np.argsort(negative)+1)

positive flows [0.51199188 0.759075   0.67112599 0.97953701]
positive flows rank [4 2 3 1]
negative flows [0.96477107 0.61254685 0.70973696 0.634675  ]
negative flows rank [2 4 3 1]


In [29]:
# net flow
PINET=np.sum(PI,axis=0)-np.sum(PI,axis=1) 
for i in range(len(PINET)):
    print(round(PINET[i],5))

-0.45278
0.14653
-0.03861
0.34486


In [30]:
np.argsort(-PINET)+1 

array([4, 2, 3, 1], dtype=int64)

6.3 Comparative analysis

Vierma’s method

In [31]:
#!/usr/bin/env python
# coding: utf-8

# @article{Verma2020,
# 	title={Multiple attribute group decision making based on 2-dimension linguistic intuitionistic fuzzy aggregation operators},
# 	author={ R. Verma  and  J. M. Merig\'{o}},
# 	journal={Soft Computing},
# 	volume={24},
# 	pages={17377-17400},
# 	year={2020},
# }

# # Definition of operation function
def oplus(a,b,t,t1):
    """ a,b:  list, 
              2DLIFV
       t,t1: int
            t+1 is the cardinality of H and t1+1 is the cardinality of S
    """
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; 
    result=[u1+v1-(u1*v1)/t,(u2*v2)/t,u3+v3-(u3*v3)/t1,(u4*v4)/t1];
    return result
def otimes(a,b,t,t1):
    """ a,b:  list, 
              2DLIFV
       t,t1: int
            t+1 is the cardinality of H and t1+1 is the cardinality of S
    """    
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];v1=b[0];v2=b[1]; v3=b[2];v4=b[3]; 
    result=[(u1*v1)/t,u2+v2-(u2*v2)/t,(u3*v3)/t1,u4+v4-(u4*v4)/t1];
    return result

def nummultiply(a,lamda,t,t1):
    """ a:  list, 
             2DLIFVs
        t,t1: int
            t+1 is the cardinality of H and t1+1 is the cardinality of S
       lamda: float
    """
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];  
    result=[t*(1-pow(1-u1/t,lamda)),t*pow(u2/t,lamda),t1*(1-pow(1-u3/t1,lamda)),t1*pow(u4/t1,lamda)];
    return result

def powmultiply(a,lamda,t,t1):
    """ a:   list, 
            2DLIFV
        t,t1: int
            t+1 is the cardinality of H and t1+1 is the cardinality of S
        lamda: float
    """
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];  
    result=[t*pow(u1/t,lamda),t*(1-pow(1-u2/t,lamda)),t1*pow(u3/t1,lamda),t1*(1-pow(1-u4/t1,lamda))];
    return result

def score(a,t,t1):
    u1=a[0];u2=a[1];u3=a[2];u4=a[3];  
    result=((t+u1-u2)/(2*t))*((t1+u3-u4)/(2*t1));
    return round(result,4)

FinalR=[]
for i in range(4):
    z=[0,8,0,4]                            
    for j in range(4):
        z=oplus(z,nummultiply(R2[j][i],w[j],8,4),8,4)
    FinalR.append(z)

aggscore=[]
for i in range(len(FinalR)):
    aggscore.append(score(FinalR[i],8,4))               
print("score",aggscore)

print("rank",np.argsort(aggscore)+1 )                    


score [0.2394, 0.3118, 0.3245, 0.3362]
rank [1 2 3 4]


Zhao’s method

In [32]:
def SA(a):
    s=a[0];h=a[1];
    tau=2;
    gama=4;
    result=(s+1)*(h+1)/((tau+1)*(gama+1));
    return round(result,4)

def PD(a1,a2):
    s1=a1[0];h1=a1[1];s2=a2[0];h2=a2[1];
    tau=2;
    gama=4;
    xi=max(h1-h2,0)*abs(s1-s2)/((tau+1)*(gama+1));
    wedge=[min(s1,s2),min(h1,h2)];
    vee=[max(s1,s2),max(h1,h2)];
    if s1<s2 and h1<=h2 or s1<=s2 and h1<h2:
        return(0)
    elif s1>s2 and h1>=h2 or s1>=s2 and h1>h2:
        return(1)
    else:
        return (SA(a1)+xi)/(SA(wedge)+SA(vee))  


def PDMatrix(a):
    result=np.zeros(len(a)*len(a)).reshape(len(a),len(a))
    for i in range(len(a)):
        for j in range(len(a)):
            result[i,j]=PD(a[i],a[j])  
    return(result)



def PDI(a):
    result=np.zeros(len(a))
    for i in range (len(a)):
        result[i]=(sum(PDMatrix(a)[i,])+len(a)/2-1)/(len(a)*(len(a)-1))
    return(result)


def PDIDFMatrix(PDIvalue):
    result=np.zeros(len(PDIvalue)*len(PDIvalue)).reshape(len(PDIvalue),len(PDIvalue))
    for i in range(len(PDIvalue)):
        for j in range(len(PDIvalue)):
            result[i,j]=PDIvalue[i]-PDIvalue[j]
    return(result)




def P1(Cn):
    PDIC=PDI(Cn)
    PDICmatrix=PDIDFMatrix(PDIC)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if PDICmatrix[i,j]<=0:
                re[i,j]=0
            else:
                re[i,j]=1
    return re




def P2(Cn,q):
    PDIC=PDI(Cn)
    PDICmatrix=PDIDFMatrix(PDIC)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if PDICmatrix[i,j]<=q:
                re[i,j]=0
            else:
                re[i,j]=1
    return re





def P3(Cn,p):
    PDIC=PDI(Cn)
    PDICmatrix=PDIDFMatrix(PDIC)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if PDICmatrix[i,j]<=0:
                re[i,j]=0
            elif PDICmatrix[i,j]>p:
                re[i,j]=1
            else:
                re[i,j]=PDICmatrix[i,j]/p
    return re





def P4(Cn,q,p):
    PDIC=PDI(Cn)
    PDICmatrix=PDIDFMatrix(PDIC)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if PDICmatrix[i,j]<=q:
                re[i,j]=0
            elif PDICmatrix[i,j]>p:
                re[i,j]=1
            else:
                re[i,j]=0.5
    return re





def P5(Cn,q,p):
    PDIC=PDI(Cn)
    PDICmatrix=PDIDFMatrix(PDIC)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if PDICmatrix[i,j]<=q:
                re[i,j]=0
            elif PDICmatrix[i,j]>p:
                re[i,j]=1
            else:
                re[i,j]=(PDICmatrix[i,j]-q)/(p-q)
    return re




def P6(Cn,sigma=1):
    PDIC=PDI(Cn)
    PDICmatrix=PDIDFMatrix(PDIC)
    re=np.zeros(len(Cn)*len(Cn)).reshape(len(Cn),len(Cn))
    for i in range(len(Cn)):
        for j in range(len(Cn)):
            if PDICmatrix[i,j]<=0:
                re[i,j]=0
            else:
                re[i,j]=round(1-np.exp(-pow(PDICmatrix[i,j],2)/(2*pow(sigma,2))),4)
    return re


e2a11=[2,1]
e2a21=[4,2]
e2a31=[2,1]
e2a41=[5,3]
e2C1=[e2a11,e2a21,e2a31,e2a41]
e2C1


# In[7]:


e2a12=[4,2]
e2a22=[2,2]
e2a32=[4,1]
e2a42=[3,1]
e2C2=[e2a12,e2a22,e2a32,e2a42]
e2C2


# In[8]:


e2a13=[2,1]
e2a23=[2,2]
e2a33=[4,2]
e2a43=[3,2]
e2C3=[e2a13,e2a23,e2a33,e2a43]
e2C3


# In[9]:


e2a14=[2,2]
e2a24=[3,1]
e2a34=[3,1]
e2a44=[4,2]
e2C4=[e2a14,e2a24,e2a34,e2a44]
e2C4


# In[10]:


R2=[e2C1,e2C2,e2C3,e2C4]   #专家E2的决策矩阵R2
R2


PI=w[0]*P5(e2C1,0.1,0.25)+w[1]*P4(e2C2,0.1,0.)+w[2]*P6(e2C3,0.3)+w[3]*P3(e2C4,0.25)
PI





positive=np.sum(PI,axis=1)
positive
np.argsort(positive)+1 

negative=np.sum(PI,axis=0) 
negative


np.argsort(negative)+1 


PINET=np.sum(PI,axis=1)-np.sum(PI,axis=0) 
for i in range(len(PINET)):
    print(round(PINET[i],5))

np.argsort(-PINET)+1    


0.43701
-0.34686
-0.55923
0.46909


array([4, 1, 2, 3], dtype=int64)